#!/usr/bin/env bash
set -eu

OUT=$1
shift
DOMAIN=$1
shift

mkdir -p $(dirname $OUT)
if [ -e pre$OUT ]
then
  cp pre$OUT $OUT
  exit 0
fi

openssl req \
  -new \
  -out $OUT \
  -config <(cat $1 | sed "s/__DOMAIN__/$DOMAIN/g") \
  -key $2
