#!/usr/bin/env bash
set -eu

OUT=$1
shift
DOMAIN=$1
shift

mkdir -p $(dirname $OUT)
if [ -e pre$OUT ]
then
  cp pre$OUT $OUT
  exit 0
fi

openssl req \
 -new \
 -x509 \
 -days 7300 \
 -out $OUT \
 -config $1 \
 -key $2
